--- #YAML:1.0
name:               Alien-LibANN
version:            0.01000
abstract:           Wrapper for installing libANN v1.1.2
author:
    - Stephan Conrad <conrad@stephanconrad.de>
license:            unknown
distribution_type:  module
configure_requires:
    Archive::Tar:  0
    File::Spec:    0
    IO::Zlib:      0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
